### ISSUE TITLE
Fix person arguments in queries and mutations

### ISSUE THREAD

**Issue by pc2752** [trompamusic/trompa-ce-client#15]
Final list: 
Creator: who added the node (link to a branch on github, software used to make it, otherwise trompamusic.eu)
Contributor: musicbrainz.org
Format: text/html
Language: en
Source: https://musicbrainz.org/artist/8d610e51-64b4-4654-b8df-064b0fb7a9d9
Title: Gustav Mahler - MusicBrainz (?)
Name: Gustav Mahler
birthDate: _Neo4jDateInput
deathDate: _Neo4jDateInput
familyName: String
gender: Gender
givenName: String
Authorities: choose which ones we want
Source: https://www.wikidata.org/entity/Q7304
Description: from english wikipedia (if lang is en), 
Image: - from wikipedia
Honorifics - if found
Job title - if found (occupation)

**Comment by alastair** [comment]
Done in https://github.com/trompamusic/trompa-ce-client/commit/4bc272a50e1233d10a739e1bdca62c537b18739b
