### ISSUE TITLE
Move ce-host settings to client application

### ISSUE THREAD

**Issue by CasperCDR** [trompamusic/trompa-ce-client#22]
The import.ini containing the ce-host address is not available at the expected location when installing the ce-data-import as library. This results in an error when using the trompa-ce-client after a clean install.

Statement: This setting should be set in the application using the library, not the library itself.

**Comment by CasperCDR** [comment]
Solution proposed in branch [fix/remove-ce-host-setting-from-file](https://github.com/trompamusic/trompa-ce-client/tree/fix/remove-ce-host-setting-from-file)

**Comment by alastair** [comment]
I updated this significantly in https://github.com/trompamusic/trompa-ce-client/commit/2fcad51a59d0337f2d824ee24a64acf42c0666fb
