### ISSUE TITLE
Creation mutations should return identidier

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#24]
The following functions:

trompace.mutations.application.mutation_create_application()
trompace.mutations.entrypoint.mutation_create_entry_point()
trompace.mutations.controlaction.mutation_create_controlaction()

shouldn't return the uuid of the created nodes?

**Comment by alastair** [comment]
Confusion between the methods used to create the mutation and the methods used to send the query to the CE (trompace.application.application)
