### ISSUE TITLE
Entrypoint-Control Action template error

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#30]
ADD_ENTRYPOINT_CONTROLACTION does not need type values EntryPoint, ControlAction:

        from: {{identifier: "{identifier_1}", type:EntryPoint}}
        to: {{identifier: "{identifier_2}", type: ControlAction}}

correction suggested in mytation_fixes branch

**Comment by alastair** [comment]
same as #5
