### ISSUE TITLE
Use CE client from external configuration file

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#39]
How is it possible to use the client for other than default local CE?

**Comment by alastair** [comment]
I've updated the example in the readme: https://github.com/trompamusic/trompa-ce-client/blob/2fcad51a59d0337f2d824ee24a64acf42c0666fb/README.md#using-the-library

You can copy the file 'trompace.ini' anywhere, and pass this full path to `config.load()`. 
If you want to use a different CE, change the `host` and `secure` items in the config file. For the MTG CE you should use:
```
[server]
host = trompa-mtg.upf.edu/ce/
secure = true
```
