### ISSUE TITLE
Update mutation methods based on new API

### ISSUE THREAD

**Issue by alastair** [trompamusic/trompa-ce-client#5]
some changes to the CE altered the way that we perform mutations to create relations: https://github.com/trompamusic/ce-api/pull/48
We need to update all of the mutations that we have to use the new method

**Comment by alastair** [comment]
I've done this with document-composition here: https://github.com/trompamusic/trompa-ce-client/commit/3ea1213367d058d7e28e511150c6616dbe6358d8

I searched the code for `field: ` and the remaining items seem to be:
 * work-composer (see also https://github.com/trompamusic/ce-api/issues/18)
 * controlaction-propertyvaluespecification
 * controlaction-property
 * digitaldocument-controlaction

**Comment by aggelosgkiokas** [comment]
ADD_CONTROLACTION_PROPERTYVALUESPECIFICATION has to be updated

**Comment by alastair** [comment]
Should be done now
