### ISSUE TITLE
Move all templates to */templates.py

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#55]
Shall we move all mutation/queries templates to the corresponding templates.py files? For example:

https://github.com/trompamusic/trompa-ce-client/blob/95cdc54979c53d2d3c567ff97ea7129f07ffe69c/trompace/mutations/property.py#L7-L11

Shall this be moved to trompace/mutations/templates.py?

**Comment by alastair** [comment]
We have some better methods for writing these kinds of queries now. See `create_mutation`:
https://github.com/trompamusic/trompa-ce-client/blob/33c98735df1ce4323b617c3a63a42d11dd4eb0db/trompace/mutations/mediaobject.py#L75

and for joining two objects, `format_link_mutation`: https://github.com/trompamusic/trompa-ce-client/blob/33c98735df1ce4323b617c3a63a42d11dd4eb0db/trompace/mutations/mediaobject.py#L153
