### ISSUE TITLE
jwt_token_cache crashes if server contains "/"

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#58]
If the host contains /, for exampe 

trompa-mtg.upf.edu/ce

then
https://github.com/trompamusic/trompa-ce-client/blob/7162a2fb622d2fd364b2aa2a99fc3077e1d52ec7/trompace/config.py#L91
it tries to store the cache in a file in a folder that does not exist

**Comment by alastair** [comment]
Thanks for reporting
